
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 05 12:27:42 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 33;
  public static final int EQUALITY = 42;
  public static final int INCREMENT = 19;
  public static final int CHAR = 50;
  public static final int CONST = 5;
  public static final int EQUALS = 6;
  public static final int NOT_EQUAL = 43;
  public static final int L_PAREN = 9;
  public static final int GREATER = 44;
  public static final int SEMI = 11;
  public static final int CONTINUE = 25;
  public static final int R_PAREN = 10;
  public static final int LESS = 46;
  public static final int FOR = 22;
  public static final int MINUS = 29;
  public static final int DECREMENT = 20;
  public static final int STATIC = 16;
  public static final int AND = 40;
  public static final int OR = 41;
  public static final int BOOL = 51;
  public static final int COMMA = 12;
  public static final int CLASS = 3;
  public static final int L_INDEXER = 13;
  public static final int LESS_EQUAL = 47;
  public static final int MODULATE_EQUALS = 37;
  public static final int PLUS = 28;
  public static final int MULTIPLY = 32;
  public static final int IF = 38;
  public static final int DIVIDE_EQUALS = 36;
  public static final int THIS = 4;
  public static final int DOT = 18;
  public static final int EOF = 0;
  public static final int RETURN = 27;
  public static final int GREATER_EQUAL = 45;
  public static final int NEW = 21;
  public static final int error = 1;
  public static final int NUMBER = 48;
  public static final int MODULATE = 34;
  public static final int IDENT = 49;
  public static final int BREAK = 26;
  public static final int VOID = 17;
  public static final int MINUS_EQUALS = 31;
  public static final int L_BRACE = 7;
  public static final int ELSE = 39;
  public static final int R_BRACE = 8;
  public static final int READ = 24;
  public static final int PLUS_EQUALS = 30;
  public static final int MULTIPLY_EQUALS = 35;
  public static final int EXTENDS = 15;
  public static final int PROG = 2;
  public static final int R_INDEXER = 14;
  public static final int PRINT = 23;
}

