
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 17 00:47:31 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 32;
  public static final int EQUALITY = 41;
  public static final int INCREMENT = 18;
  public static final int CHAR = 49;
  public static final int CONST = 4;
  public static final int EQUALS = 5;
  public static final int NOT_EQUAL = 42;
  public static final int L_PAREN = 8;
  public static final int GREATER = 43;
  public static final int SEMI = 10;
  public static final int CONTINUE = 24;
  public static final int R_PAREN = 9;
  public static final int LESS = 45;
  public static final int FOR = 21;
  public static final int MINUS = 28;
  public static final int DECREMENT = 19;
  public static final int STATIC = 15;
  public static final int AND = 39;
  public static final int OR = 40;
  public static final int BOOL = 50;
  public static final int COMMA = 11;
  public static final int CLASS = 3;
  public static final int L_INDEXER = 12;
  public static final int LESS_EQUAL = 46;
  public static final int MODULATE_EQUALS = 36;
  public static final int PLUS = 27;
  public static final int MULTIPLY = 31;
  public static final int IF = 37;
  public static final int DIVIDE_EQUALS = 35;
  public static final int DOT = 17;
  public static final int EOF = 0;
  public static final int RETURN = 26;
  public static final int GREATER_EQUAL = 44;
  public static final int NEW = 20;
  public static final int error = 1;
  public static final int NUMBER = 47;
  public static final int MODULATE = 33;
  public static final int IDENT = 48;
  public static final int BREAK = 25;
  public static final int VOID = 16;
  public static final int MINUS_EQUALS = 30;
  public static final int L_BRACE = 6;
  public static final int ELSE = 38;
  public static final int R_BRACE = 7;
  public static final int READ = 23;
  public static final int PLUS_EQUALS = 29;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int MULTIPLY_EQUALS = 34;
  public static final int R_INDEXER = 13;
  public static final int PRINT = 22;
}

