
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 14 23:42:20 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 27;
  public static final int INCREMENT = 19;
  public static final int CONST = 5;
  public static final int CHAR = 34;
  public static final int EQUALS = 6;
  public static final int L_PAREN = 9;
  public static final int SEMI = 11;
  public static final int R_PAREN = 10;
  public static final int MINUS = 23;
  public static final int DECREMENT = 20;
  public static final int STATIC = 16;
  public static final int BOOL = 35;
  public static final int COMMA = 12;
  public static final int CLASS = 3;
  public static final int L_INDEXER = 13;
  public static final int MODULATE_EQUALS = 31;
  public static final int PLUS = 22;
  public static final int MULTIPLY = 26;
  public static final int DIVIDE_EQUALS = 30;
  public static final int DOT = 18;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int NUMBER = 32;
  public static final int MODULATE = 28;
  public static final int IDENT = 33;
  public static final int VOID = 17;
  public static final int MINUS_EQUALS = 25;
  public static final int L_BRACE = 7;
  public static final int R_BRACE = 8;
  public static final int PLUS_EQUALS = 24;
  public static final int EXTENDS = 15;
  public static final int PROG = 2;
  public static final int MULTIPLY_EQUALS = 29;
  public static final int TERMSTUB = 21;
  public static final int R_INDEXER = 14;
  public static final int PRINT = 4;
}

